version: '3'
services:
  voltdb-node-HOME:
    ports:
      - '21212'
      - '21211'
      - '8080'
      - '3021'
    image: 'voltdb/voltdb-community:latest'
    environment:
      - 'HOSTCOUNT=1'
      - 'HOSTS=voltdb-node-HOME'
    entrypoint: >
      sh -c "if [ ! -d "/var/voltdb/voltdbroot/" ]; then 
            voltdb init -C /opt/voltdb/deployment.xml -D /var/voltdb/
            fi &&
            voltdb start -H voltdb-node-MILAD -D /var/voltdb/ --ignore=thp"
    volumes:
      - /mnt/storage/HOME/data/voltdb:/var/voltdb
      - /data:/data:ro
