version: "3.5"

services:

  # Apache Spark

  hdfs-spark-master-HOME:
    image: gettyimages/spark:2.3.0-hadoop-2.8
    command: bin/spark-class org.apache.spark.deploy.master.Master -h master
    container_name: spark-master
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_PUBLIC_DNS: localhost
      CORE_CONF_fs_defaultFS: hdfs://hdfs:8020
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
      - 4040
      - 8080
    links:
      - hdfs-namenode-HOME:namenode
    volumes:
      - ./conf/master:/conf
      - /data:/data:ro


  hdfs-spark-worker-HOME:
    image: gettyimages/spark:2.3.0-hadoop-2.8
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    container_name: spark-worker
    hostname: worker
    environment:
      SPARK_MASTER: spark://master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      CORE_CONF_fs_defaultFS: hdfs://hdfs:8020
    links:
      - hdfs-spark-master:master
      - hdfs-namenode-HOME:namenode
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
      - 8081
    volumes:
      - ./conf/master:/conf
      - /data:/data:ro

  # Apache Flink

  hdfs-flink-jobmanager-HOME:
    image: flink:1.6.2-hadoop28
    container_name: flink-jobmanager
    expose:
      - "6123"
      - "8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=hdfs-flink-jobmanager-HOME
    links:
      - hdfs-namenode-HOME:namenode

  hdfs-flink-taskmanager-HOME:
    image: flink:1.6.2-hadoop28
    container_name: flink-taskmanager
    expose:
      - "6121"
      - "6122"
    depends_on:
      - hdfs-flink-jobmanager-HOME
    command: taskmanager
    links:
      - hdfs-flink-jobmanager-HOME:jobmanager
      - hdfs-namenode-HOME:namenode
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  # HDFS

  hdfs-namenode-HOME:
    image: bde2020/hadoop-namenode:1.2.1-hadoop2.8-java8
    container_name: namenode
    volumes:
      - /mnt/storage/HOME/data/hdfs/nodename:/hadoop/dfs/name
      - /data:/data:ro
    environment:
      - CLUSTER_NAME=db
    env_file:
      - ./hadoop.env

  hdfs-resourcemanager-HOME:
    image: bde2020/hadoop-resourcemanager:1.2.1-hadoop2.8-java8
    container_name: resourcemanager
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop.env

  hdfs-historyserver-HOME:
    image: bde2020/hadoop-historyserver:1.2.1-hadoop2.8-java8
    container_name: historyserver
    depends_on:
      - namenode
      - datanode
    volumes:
      - /mnt/storage/HOME/data/hdfs/historyserver:/hadoop/yarn/timeline
      - /data:/data:ro
    env_file:
      - ./hadoop.env

  hdfs-nodemanager-HOME:
    image: bde2020/hadoop-nodemanager:1.2.1-hadoop2.8-java8
    container_name: nodemanager
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop.env

  hdfs-datanode-HOME:
    image: bde2020/hadoop-datanode:1.2.1-hadoop2.8-java8
    container_name: datanode
    depends_on:
      - namenode
    volumes:
      - /mnt/storage/HOME/data/hdfs/datanode:/hadoop/dfs/data
      - /data:/data:ro
    env_file:
      - ./hadoop.env
