version: '2'

services:
  roach-HOME:
    container_name: cockroach
    image: cockroachdb/cockroach:latest
    command: start --insecure
    volumes:
      - /mnt/storage/HOME/data/cockroach:/cockroach/cockroach-data
      - /data:/data:ro
