postgres:
  image: postgres:latest
  expose:
    - 5432
  restart: always
  shm_size: 512M
  volumes:
    - ./data:/var/lib/postgresql/data
  environment:
    POSTGRES_PASSWORD: root
    POSTGRES_USER: root
