postgres-HOME:
  image: postgres:latest
  expose:
    - 5432
  restart: always
  shm_size: 512M
  volumes:
    - /mnt/storage/HOME/data/postgres:/var/lib/postgresql/data
    - /data:/data:ro
  environment:
    POSTGRES_PASSWORD: root
    POSTGRES_USER: root
